### ISSUE TITLE
What are the "fakes" types?

### ISSUE THREAD

**Issue by MrSapps** [stohrendorf/symdump#3]
What are all of those .fake types? Is there some description or docs on what this means?

**Comment by stohrendorf** [comment]
These are anonymous types. Say, for example, you write something like
```C
typedef struct {} foo;
```
or
```C
struct { union { int baz; } foo; } bar;
```
then the `foo` struct and the union are anonymous. The compiler creates in this case an artificial name. The internal representation of these would be something like:
* `typedef foo` is typedef for `struct .fake123`
*  `struct bar` has a member `foo` of type `union .fake456`

If you have further questions, I'll be glad to answer them, otherwise please close this ticket.
